# Full configuration reference: https://github.com/csarrazi/CsaGuzzleBundle/blob/2.x/src/Resources/doc/configuration_reference.md#configuration-reference
# Available client config options: http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client
# and http://docs.guzzlephp.org/en/latest/request-options.html
csa_guzzle:
    profiler:
        enabled: '%kernel.debug%'
    logger:
        enabled: '%kernel.debug%'
    clients:
        authentication:
            config:
                base_uri: 'https://%env(SERVICE_AUTHENTICATION_BASEURI)%'
                timeout: 2.0
                verfify: true
                headers:
                    Accept: application/ld+json
            middleware: ['debug', 'stopwatch', 'logger', 'bearer']
