name: myapp
recipe: lemp
config:
    webroot: public
    database: mariadb
    xdebug: true

proxy:
    pma:
        - pma.lemp.lndo.site

services:
    appserver:
        type: "php"
        version: "7.2"
        config:
            server: nginx.conf
    # Add a phpmyadmin db frontend
    pma:

        # Use the latest version of phpmyadmin
        type: phpmyadmin

        # The databases you want to look at, this will default to a service called
        # "database"
        #
        # You might want to run `lando info` on your app to see what databases you
        # have available
        hosts:
            - database

              # Optionally load in a custom config file. This is relative to the app root
              #
              # You will not need to import the standard library or manage backends in this
              # file. Those are handled automatically.
              #
              # config: config.user.inc.php

              # There are various envvars you can specify to further customize how your
              # pma works.
              #
              # See: https://hub.docker.com/r/phpmyadmin/phpmyadmin/
              #
              # overrides:
              # services:
              # environment:
              # PMA_ARBITRARY: when set to 1 connection to the arbitrary server will be allowed
              # PMA_HOST: define address/host name of the MySQL server
              # PMA_VERBOSE: define verbose name of the MySQL server
              # PMA_PORT: define port of the MySQL server
              # PMA_HOSTS: define comma separated list of address/host names of the MySQL servers
              # PMA_VERBOSES: define comma separated list of verbose names of the MySQL servers
              # PMA_USER: define username to use for config authentication method
              # PMA_PASSWORD: define password to use for config authentication method
            # PMA_ABSOLUTE_URI: define user-facing URI
tooling:
    sf:
        service: appserver
        description: "Run Symfony commands: lando sf [command]"
        cmd:
            - bin/console
    phpunit:
        service: appserver
        description: "Run PHP Unit tests: lando phpunit [options]"
        cmd:
            - bin/phpunit --colors=always --coverage-html=build/phpunit/coverage
    phplint:
        service: appserver
        description: "Run PHP lint: lando phplint [options]"
        cmd:
            - vendor/bin/phplint -vvv --no-cache --configuration=./.phplint.yml
    phpmetrics:
        service: appserver
        description: "Run PHP metrics: lando phpmetrics [options]"
        cmd:
            - vendor/bin/phpmetrics --report-html=build/phpmetrics src/
events:
    post-start:
        - appserver: "bin/console doctrine:migration:migrate --no-interaction"
        - appserver: "bin/console doctrine:schema:validate"
