name: myapp
recipe: lemp
config:
    webroot: public
    database: mariadb
    xdebug: true

proxy:
    appserver:
        - redis.lndo.site
    pma:
        - pma.lemp.lndo.site

services:
    appserver:
        type: "php"
        version: "7.2"
        config:
            server: nginx.conf

    cache:
        type: redis:4.0
        portforward: 6380
        persist: true

    database:
        creds:
            user: lemp
            password: lemp
            database: myapp

    pma:
        type: phpmyadmin
        hosts:
            - database

tooling:
    redis-cli:
        service: cache
    sf:
        service: appserver
        description: "Run Symfony commands: lando sf [command]"
        cmd:
            - bin/console
    phpunit:
        service: appserver
        description: "Run PHP Unit tests: lando phpunit [options]"
        cmd:
            - bin/phpunit --colors=always --coverage-html=build/phpunit/coverage
    phplint:
        service: appserver
        description: "Run PHP lint: lando phplint [options]"
        cmd:
            - vendor/bin/phplint -vvv --no-cache --configuration=./.phplint.yml
    phpmetrics:
        service: appserver
        description: "Run PHP metrics: lando phpmetrics [options]"
        cmd:
            - vendor/bin/phpmetrics --report-html=build/phpmetrics src/
events:
    post-start:
        - appserver: "bin/console doctrine:migration:migrate --no-interaction"
        - appserver: "bin/console doctrine:schema:validate"

        - appserver: "bin/console app::auth:register"
        - appserver: "bin/console app::auth:token"
